"""Initial migration

Revision ID: 029092c13c1f
Revises: 0ec43e230684
Create Date: 2025-04-01 18:27:29.979144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029092c13c1f'
down_revision = '0ec43e230684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_data')
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_index('idx_artist_name')

    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_index('idx_rating')
        batch_op.drop_index('idx_title_gist', postgresql_using='gist')
        batch_op.drop_index('idx_title_trgm', postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.create_index('idx_title_trgm', ['title'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_title_gist', ['title'], unique=False, postgresql_using='gist')
        batch_op.create_index('idx_rating', ['rating'], unique=False)

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.create_index('idx_artist_name', ['artist_name'], unique=False)

    op.create_table('temp_data',
    sa.Column('artist_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
