"""Update verification fields for code-based verification

Revision ID: 0ec43e230684
Revises: 44942b56d998
Create Date: 2025-03-31 20:15:33.048154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ec43e230684'
down_revision = '44942b56d998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('verification_code_expiry', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('user_verification_token_key', type_='unique')
        batch_op.drop_column('verification_token_expiry')
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('verification_token_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_verification_token_key', ['verification_token'])
        batch_op.drop_column('verification_code_expiry')
        batch_op.drop_column('verification_code')

    # ### end Alembic commands ###
