"""Add url column to works table

Revision ID: ba0442fa403c
Revises: 029092c13c1f
Create Date: 2025-04-01 20:25:39.186790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0442fa403c'
down_revision = '029092c13c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_index('idx_artist_name')

    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=500), nullable=True))
        batch_op.drop_index('idx_rating')
        batch_op.drop_index('idx_title_gist', postgresql_using='gist')
        batch_op.drop_index('idx_title_trgm', postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.create_index('idx_title_trgm', ['title'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_title_gist', ['title'], unique=False, postgresql_using='gist')
        batch_op.create_index('idx_rating', ['rating'], unique=False)
        batch_op.drop_column('url')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.create_index('idx_artist_name', ['artist_name'], unique=False)

    # ### end Alembic commands ###
